# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: social/mixi/application/model/v1/community.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'social/mixi/application/model/v1/community.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from social.mixi.application.const.v1 import community_access_level_pb2 as social_dot_mixi_dot_application_dot_const_dot_v1_dot_community__access__level__pb2
from social.mixi.application.const.v1 import community_visibility_pb2 as social_dot_mixi_dot_application_dot_const_dot_v1_dot_community__visibility__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n0social/mixi/application/model/v1/community.proto\x12 social.mixi.application.model.v1\x1a=social/mixi/application/const/v1/community_access_level.proto\x1a;social/mixi/application/const/v1/community_visibility.proto\"\xee\x01\n\tCommunity\x12\x14\n\x0c\x63ommunity_id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0f\n\x07purpose\x18\x03 \x01(\t\x12\x13\n\x0bis_archived\x18\x04 \x01(\x08\x12I\n\nvisibility\x18\x05 \x01(\x0e\x32\x35.social.mixi.application.const.v1.CommunityVisibility\x12L\n\x0c\x61\x63\x63\x65ss_level\x18\x06 \x01(\x0e\x32\x36.social.mixi.application.const.v1.CommunityAccessLevel\"{\n\x19\x43ommunityUsingApplication\x12>\n\tcommunity\x18\x01 \x01(\x0b\x32+.social.mixi.application.model.v1.Community\x12\x1e\n\x16\x61pplication_version_id\x18\x02 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'social.mixi.application.model.v1.community_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_COMMUNITY']._serialized_start=211
  _globals['_COMMUNITY']._serialized_end=449
  _globals['_COMMUNITYUSINGAPPLICATION']._serialized_start=451
  _globals['_COMMUNITYUSINGAPPLICATION']._serialized_end=574
# @@protoc_insertion_point(module_scope)
