# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: social/mixi/application/model/v1/media.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'social/mixi/application/model/v1/media.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from social.mixi.application.const.v1 import media_type_pb2 as social_dot_mixi_dot_application_dot_const_dot_v1_dot_media__type__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n,social/mixi/application/model/v1/media.proto\x12 social.mixi.application.model.v1\x1a\x31social/mixi/application/const/v1/media_type.proto\"\xd1\x01\n\x05Media\x12?\n\nmedia_type\x18\x01 \x01(\x0e\x32+.social.mixi.application.const.v1.MediaType\x12=\n\x05image\x18\x02 \x01(\x0b\x32,.social.mixi.application.model.v1.MediaImageH\x00\x12=\n\x05video\x18\x03 \x01(\x0b\x32,.social.mixi.application.model.v1.MediaVideoH\x00\x42\t\n\x07\x63ontent\"\xea\x01\n\nMediaImage\x12\x17\n\x0flarge_image_url\x18\x01 \x01(\t\x12\x1d\n\x15large_image_mime_type\x18\x02 \x01(\t\x12\x1a\n\x12large_image_height\x18\x03 \x01(\r\x12\x19\n\x11large_image_width\x18\x04 \x01(\r\x12\x17\n\x0fsmall_image_url\x18\x05 \x01(\t\x12\x1d\n\x15small_image_mime_type\x18\x06 \x01(\t\x12\x1a\n\x12small_image_height\x18\x07 \x01(\r\x12\x19\n\x11small_image_width\x18\x08 \x01(\r\"\xec\x01\n\nMediaVideo\x12\x11\n\tvideo_url\x18\x01 \x01(\t\x12\x17\n\x0fvideo_mime_type\x18\x02 \x01(\t\x12\x14\n\x0cvideo_height\x18\x03 \x01(\r\x12\x13\n\x0bvideo_width\x18\x04 \x01(\r\x12\x19\n\x11preview_image_url\x18\x05 \x01(\t\x12\x1f\n\x17preview_image_mime_type\x18\x06 \x01(\t\x12\x1c\n\x14preview_image_height\x18\x07 \x01(\r\x12\x1b\n\x13preview_image_width\x18\x08 \x01(\r\x12\x10\n\x08\x64uration\x18\t \x01(\x02\"K\n\nMediaStamp\x12\x0b\n\x03url\x18\x01 \x01(\t\x12\x11\n\tmime_type\x18\x02 \x01(\t\x12\x0e\n\x06height\x18\x03 \x01(\r\x12\r\n\x05width\x18\x04 \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'social.mixi.application.model.v1.media_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MEDIA']._serialized_start=134
  _globals['_MEDIA']._serialized_end=343
  _globals['_MEDIAIMAGE']._serialized_start=346
  _globals['_MEDIAIMAGE']._serialized_end=580
  _globals['_MEDIAVIDEO']._serialized_start=583
  _globals['_MEDIAVIDEO']._serialized_end=819
  _globals['_MEDIASTAMP']._serialized_start=821
  _globals['_MEDIASTAMP']._serialized_end=896
# @@protoc_insertion_point(module_scope)
