# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: social/mixi/application/model/v1/stamp.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'social/mixi/application/model/v1/stamp.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from social.mixi.application.const.v1 import stamp_set_type_pb2 as social_dot_mixi_dot_application_dot_const_dot_v1_dot_stamp__set__type__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n,social/mixi/application/model/v1/stamp.proto\x12 social.mixi.application.model.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x35social/mixi/application/const/v1/stamp_set_type.proto\"\xcf\x02\n\x10OfficialStampSet\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x12\n\nsprite_url\x18\x02 \x01(\t\x12?\n\x06stamps\x18\x03 \x03(\x0b\x32/.social.mixi.application.model.v1.OfficialStamp\x12\x14\n\x0cstamp_set_id\x18\x04 \x01(\t\x12\x31\n\x08start_at\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.TimestampH\x00\x88\x01\x01\x12/\n\x06\x65nd_at\x18\x06 \x01(\x0b\x32\x1a.google.protobuf.TimestampH\x01\x88\x01\x01\x12\x46\n\x0estamp_set_type\x18\x07 \x01(\x0e\x32..social.mixi.application.const.v1.StampSetTypeB\x0b\n\t_start_atB\t\n\x07_end_at\"R\n\rOfficialStamp\x12\x10\n\x08stamp_id\x18\x01 \x01(\t\x12\r\n\x05index\x18\x02 \x01(\r\x12\x13\n\x0bsearch_tags\x18\x03 \x03(\t\x12\x0b\n\x03url\x18\x04 \x01(\t\"k\n\x11\x43ommunityStampSet\x12\x14\n\x0c\x63ommunity_id\x18\x01 \x01(\t\x12@\n\x06stamps\x18\x02 \x03(\x0b\x32\x30.social.mixi.application.model.v1.CommunityStamp\"D\n\x0e\x43ommunityStamp\x12\x10\n\x08stamp_id\x18\x01 \x01(\t\x12\x0b\n\x03url\x18\x02 \x01(\t\x12\x13\n\x0bsearch_tags\x18\x03 \x03(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'social.mixi.application.model.v1.stamp_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_OFFICIALSTAMPSET']._serialized_start=171
  _globals['_OFFICIALSTAMPSET']._serialized_end=506
  _globals['_OFFICIALSTAMP']._serialized_start=508
  _globals['_OFFICIALSTAMP']._serialized_end=590
  _globals['_COMMUNITYSTAMPSET']._serialized_start=592
  _globals['_COMMUNITYSTAMPSET']._serialized_end=699
  _globals['_COMMUNITYSTAMP']._serialized_start=701
  _globals['_COMMUNITYSTAMP']._serialized_end=769
# @@protoc_insertion_point(module_scope)
