# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: social/mixi/application/model/v1/user.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'social/mixi/application/model/v1/user.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from social.mixi.application.const.v1 import user_access_level_pb2 as social_dot_mixi_dot_application_dot_const_dot_v1_dot_user__access__level__pb2
from social.mixi.application.const.v1 import user_visibility_pb2 as social_dot_mixi_dot_application_dot_const_dot_v1_dot_user__visibility__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n+social/mixi/application/model/v1/user.proto\x12 social.mixi.application.model.v1\x1a\x38social/mixi/application/const/v1/user_access_level.proto\x1a\x36social/mixi/application/const/v1/user_visibility.proto\"\xb3\x02\n\x04User\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x13\n\x0bis_disabled\x18\x02 \x01(\x08\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x14\n\x0c\x64isplay_name\x18\x04 \x01(\t\x12\x0f\n\x07profile\x18\x05 \x01(\t\x12\x41\n\x0buser_avatar\x18\x06 \x01(\x0b\x32,.social.mixi.application.model.v1.UserAvatar\x12\x44\n\nvisibility\x18\x07 \x01(\x0e\x32\x30.social.mixi.application.const.v1.UserVisibility\x12G\n\x0c\x61\x63\x63\x65ss_level\x18\x08 \x01(\x0e\x32\x31.social.mixi.application.const.v1.UserAccessLevel\"\xea\x01\n\nUserAvatar\x12\x17\n\x0flarge_image_url\x18\x01 \x01(\t\x12\x1d\n\x15large_image_mime_type\x18\x02 \x01(\t\x12\x1a\n\x12large_image_height\x18\x03 \x01(\r\x12\x19\n\x11large_image_width\x18\x04 \x01(\r\x12\x17\n\x0fsmall_image_url\x18\x05 \x01(\t\x12\x1d\n\x15small_image_mime_type\x18\x06 \x01(\t\x12\x1a\n\x12small_image_height\x18\x07 \x01(\r\x12\x19\n\x11small_image_width\x18\x08 \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'social.mixi.application.model.v1.user_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USER']._serialized_start=196
  _globals['_USER']._serialized_end=503
  _globals['_USERAVATAR']._serialized_start=506
  _globals['_USERAVATAR']._serialized_end=740
# @@protoc_insertion_point(module_scope)
