version: 2 # circle ci のversion

jobs:
  build:
    docker:
      - image: circleci/python:3.8

    working_directory: ~/hometamon

    steps:
      - checkout # code to docker image

      - run: 
          name: install dependencies
          command: |
            pip install tweepy==3.8.0
            pip install pytest==5.4.1
            pip install pytest-mock==3.1.0
            pip install python-dotenv==0.10.5

      - run:
          name: Test
          command: |
            mkdir test-reports
            cd main
            pytest --junitxml=test-reports/junit.xml

      - store_test_results:
          path: test-reports
