version: 2 # circle ci のversion

jobs:
  build:
    docker:
      -image: circleci/python:3.8

    working_directory: ~/main

    steps:
      - checkout # code to docker image

      - run: 
        name: install dependencies
        command: |
          pip install
          pip tweepy==3.8.0\
          pip pytest==5.4.1\
          pip pytest-mock==3.1.0

      - run:
        name: Test
        command: pytest

      # - store_test_results:
      #   path: test-results
      # - store_artifacts:
      #   path: test-results
      #   destination: tr1