version: 2 # circle ci のversion

jobs:
  build:
    working_directory: ~/main
    docker:
      -image: circleci/python:3.8
    steps:
      - checkout # code to docker image
      - run:
        command: | # Pipenv を使用して依存関係をインストール
          sudo pip install \
          tweepy==3.8.0\
          pytest==5.4.1\
          pytest-mock==3.1.0
        command: |
          pytest

      - store_test_results:
        path: test-results
      - store_artifacts:
        path: test-results
        destination: tr1

      
