# Generated by Django 3.0.4 on 2020-08-21 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('user_id', models.BigIntegerField()),
                ('screen_name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('secret_status', models.CharField(choices=[('secret', '鍵垢'), ('public', '公開垢')], default='secret', max_length=8)),
            ],
        ),
    ]
