post:
	curl -X POST  -H "Content-Type:application/json" \
    -d '{"user_name":"test", "user_id":112, "screen_name":"yosyuaomenw", "secret_status": "public"}' \
    http://localhost:8001/api/users/


get:
	curl -X GET http://localhost:8001/api/users/1/