# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: social/mixi/application/const/v1/community_visibility.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'social/mixi/application/const/v1/community_visibility.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n;social/mixi/application/const/v1/community_visibility.proto\x12 social.mixi.application.const.v1*\x81\x01\n\x13\x43ommunityVisibility\x12$\n COMMUNITY_VISIBILITY_UNSPECIFIED\x10\x00\x12 \n\x1c\x43OMMUNITY_VISIBILITY_VISIBLE\x10\x01\x12\"\n\x1e\x43OMMUNITY_VISIBILITY_INVISIBLE\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'social.mixi.application.const.v1.community_visibility_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_COMMUNITYVISIBILITY']._serialized_start=98
  _globals['_COMMUNITYVISIBILITY']._serialized_end=227
# @@protoc_insertion_point(module_scope)
