# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: social/mixi/application/const/v1/event_type.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'social/mixi/application/const/v1/event_type.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n1social/mixi/application/const/v1/event_type.proto\x12 social.mixi.application.const.v1*\x97\x03\n\x0b\x45ventReason\x12\x1c\n\x18\x45VENT_REASON_UNSPECIFIED\x10\x00\x12\x15\n\x11\x45VENT_REASON_PING\x10\x01\x12\x1b\n\x17\x45VENT_REASON_POST_REPLY\x10\x02\x12\x1f\n\x1b\x45VENT_REASON_POST_MENTIONED\x10\x03\x12\x1c\n\x18\x45VENT_REASON_POST_QUOTED\x10\x04\x12\x1f\n\x1b\x45VENT_REASON_POST_COMMUNITY\x10\x05\x12(\n$EVENT_REASON_COMMUNITY_MEMBER_JOINED\x10\x06\x12&\n\"EVENT_REASON_COMMUNITY_MEMBER_LEFT\x10\x07\x12(\n$EVENT_REASON_DIRECT_MESSAGE_RECEIVED\x10\x08\x12+\n\'EVENT_REASON_COMMUNITY_PLUGIN_INSTALLED\x10\t\x12-\n)EVENT_REASON_COMMUNITY_PLUGIN_UNINSTALLED\x10\n*\xd1\x01\n\tEventType\x12\x1a\n\x16\x45VENT_TYPE_UNSPECIFIED\x10\x00\x12\x13\n\x0f\x45VENT_TYPE_PING\x10\x01\x12\x1b\n\x17\x45VENT_TYPE_POST_CREATED\x10\x02\x12\'\n#EVENT_TYPE_COMMUNITY_MEMBER_CHANGED\x10\x03\x12$\n EVENT_TYPE_CHAT_MESSAGE_RECEIVED\x10\x04\x12\'\n#EVENT_TYPE_COMMUNITY_PLUGIN_MANAGED\x10\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'social.mixi.application.const.v1.event_type_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EVENTREASON']._serialized_start=88
  _globals['_EVENTREASON']._serialized_end=495
  _globals['_EVENTTYPE']._serialized_start=498
  _globals['_EVENTTYPE']._serialized_end=707
# @@protoc_insertion_point(module_scope)
