# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: social/mixi/application/const/v1/language_code.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'social/mixi/application/const/v1/language_code.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n4social/mixi/application/const/v1/language_code.proto\x12 social.mixi.application.const.v1*Y\n\x0cLanguageCode\x12\x1d\n\x19LANGUAGE_CODE_UNSPECIFIED\x10\x00\x12\x14\n\x10LANGUAGE_CODE_JP\x10\x01\x12\x14\n\x10LANGUAGE_CODE_EN\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'social.mixi.application.const.v1.language_code_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LANGUAGECODE']._serialized_start=90
  _globals['_LANGUAGECODE']._serialized_end=179
# @@protoc_insertion_point(module_scope)
