# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from social.mixi.application.service.application_api.v1 import service_pb2 as social_dot_mixi_dot_application_dot_service_dot_application__api_dot_v1_dot_service__pb2

GRPC_GENERATED_VERSION = '1.81.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in social/mixi/application/service/application_api/v1/service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ApplicationServiceStub:
    """mixi2 アプリケーションサービスです。
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetUsers = channel.unary_unary(
                '/social.mixi.application.service.application_api.v1.ApplicationService/GetUsers',
                request_serializer=social_dot_mixi_dot_application_dot_service_dot_application__api_dot_v1_dot_service__pb2.GetUsersRequest.SerializeToString,
                response_deserializer=social_dot_mixi_dot_application_dot_service_dot_application__api_dot_v1_dot_service__pb2.GetUsersResponse.FromString,
                _registered_method=True)
        self.GetPosts = channel.unary_unary(
                '/social.mixi.application.service.application_api.v1.ApplicationService/GetPosts',
                request_serializer=social_dot_mixi_dot_application_dot_service_dot_application__api_dot_v1_dot_service__pb2.GetPostsRequest.SerializeToString,
                response_deserializer=social_dot_mixi_dot_application_dot_service_dot_application__api_dot_v1_dot_service__pb2.GetPostsResponse.FromString,
                _registered_method=True)
        self.GetCommunities = channel.unary_unary(
                '/social.mixi.application.service.application_api.v1.ApplicationService/GetCommunities',
                request_serializer=social_dot_mixi_dot_application_dot_service_dot_application__api_dot_v1_dot_service__pb2.GetCommunitiesRequest.SerializeToString,
                response_deserializer=social_dot_mixi_dot_application_dot_service_dot_application__api_dot_v1_dot_service__pb2.GetCommunitiesResponse.FromString,
                _registered_method=True)
        self.CreatePost = channel.unary_unary(
                '/social.mixi.application.service.application_api.v1.ApplicationService/CreatePost',
                request_serializer=social_dot_mixi_dot_application_dot_service_dot_application__api_dot_v1_dot_service__pb2.CreatePostRequest.SerializeToString,
                response_deserializer=social_dot_mixi_dot_application_dot_service_dot_application__api_dot_v1_dot_service__pb2.CreatePostResponse.FromString,
                _registered_method=True)
        self.DeletePost = channel.unary_unary(
                '/social.mixi.application.service.application_api.v1.ApplicationService/DeletePost',
                request_serializer=social_dot_mixi_dot_application_dot_service_dot_application__api_dot_v1_dot_service__pb2.DeletePostRequest.SerializeToString,
                response_deserializer=social_dot_mixi_dot_application_dot_service_dot_application__api_dot_v1_dot_service__pb2.DeletePostResponse.FromString,
                _registered_method=True)
        self.InitiatePostMediaUpload = channel.unary_unary(
                '/social.mixi.application.service.application_api.v1.ApplicationService/InitiatePostMediaUpload',
                request_serializer=social_dot_mixi_dot_application_dot_service_dot_application__api_dot_v1_dot_service__pb2.InitiatePostMediaUploadRequest.SerializeToString,
                response_deserializer=social_dot_mixi_dot_application_dot_service_dot_application__api_dot_v1_dot_service__pb2.InitiatePostMediaUploadResponse.FromString,
                _registered_method=True)
        self.GetPostMediaStatus = channel.unary_unary(
                '/social.mixi.application.service.application_api.v1.ApplicationService/GetPostMediaStatus',
                request_serializer=social_dot_mixi_dot_application_dot_service_dot_application__api_dot_v1_dot_service__pb2.GetPostMediaStatusRequest.SerializeToString,
                response_deserializer=social_dot_mixi_dot_application_dot_service_dot_application__api_dot_v1_dot_service__pb2.GetPostMediaStatusResponse.FromString,
                _registered_method=True)
        self.GetCommunityTimeline = channel.unary_unary(
                '/social.mixi.application.service.application_api.v1.ApplicationService/GetCommunityTimeline',
                request_serializer=social_dot_mixi_dot_application_dot_service_dot_application__api_dot_v1_dot_service__pb2.GetCommunityTimelineRequest.SerializeToString,
                response_deserializer=social_dot_mixi_dot_application_dot_service_dot_application__api_dot_v1_dot_service__pb2.GetCommunityTimelineResponse.FromString,
                _registered_method=True)
        self.GetCommunityMemberList = channel.unary_unary(
                '/social.mixi.application.service.application_api.v1.ApplicationService/GetCommunityMemberList',
                request_serializer=social_dot_mixi_dot_application_dot_service_dot_application__api_dot_v1_dot_service__pb2.GetCommunityMemberListRequest.SerializeToString,
                response_deserializer=social_dot_mixi_dot_application_dot_service_dot_application__api_dot_v1_dot_service__pb2.GetCommunityMemberListResponse.FromString,
                _registered_method=True)
        self.RestrictCommunityPost = channel.unary_unary(
                '/social.mixi.application.service.application_api.v1.ApplicationService/RestrictCommunityPost',
                request_serializer=social_dot_mixi_dot_application_dot_service_dot_application__api_dot_v1_dot_service__pb2.RestrictCommunityPostRequest.SerializeToString,
                response_deserializer=social_dot_mixi_dot_application_dot_service_dot_application__api_dot_v1_dot_service__pb2.RestrictCommunityPostResponse.FromString,
                _registered_method=True)
        self.GetCommunitiesUsingApplication = channel.unary_unary(
                '/social.mixi.application.service.application_api.v1.ApplicationService/GetCommunitiesUsingApplication',
                request_serializer=social_dot_mixi_dot_application_dot_service_dot_application__api_dot_v1_dot_service__pb2.GetCommunitiesUsingApplicationRequest.SerializeToString,
                response_deserializer=social_dot_mixi_dot_application_dot_service_dot_application__api_dot_v1_dot_service__pb2.GetCommunitiesUsingApplicationResponse.FromString,
                _registered_method=True)
        self.SendChatMessage = channel.unary_unary(
                '/social.mixi.application.service.application_api.v1.ApplicationService/SendChatMessage',
                request_serializer=social_dot_mixi_dot_application_dot_service_dot_application__api_dot_v1_dot_service__pb2.SendChatMessageRequest.SerializeToString,
                response_deserializer=social_dot_mixi_dot_application_dot_service_dot_application__api_dot_v1_dot_service__pb2.SendChatMessageResponse.FromString,
                _registered_method=True)
        self.GetStamps = channel.unary_unary(
                '/social.mixi.application.service.application_api.v1.ApplicationService/GetStamps',
                request_serializer=social_dot_mixi_dot_application_dot_service_dot_application__api_dot_v1_dot_service__pb2.GetStampsRequest.SerializeToString,
                response_deserializer=social_dot_mixi_dot_application_dot_service_dot_application__api_dot_v1_dot_service__pb2.GetStampsResponse.FromString,
                _registered_method=True)
        self.AddStampToPost = channel.unary_unary(
                '/social.mixi.application.service.application_api.v1.ApplicationService/AddStampToPost',
                request_serializer=social_dot_mixi_dot_application_dot_service_dot_application__api_dot_v1_dot_service__pb2.AddStampToPostRequest.SerializeToString,
                response_deserializer=social_dot_mixi_dot_application_dot_service_dot_application__api_dot_v1_dot_service__pb2.AddStampToPostResponse.FromString,
                _registered_method=True)
        self.SendDirectMessageToCommunityMember = channel.unary_unary(
                '/social.mixi.application.service.application_api.v1.ApplicationService/SendDirectMessageToCommunityMember',
                request_serializer=social_dot_mixi_dot_application_dot_service_dot_application__api_dot_v1_dot_service__pb2.SendDirectMessageToCommunityMemberRequest.SerializeToString,
                response_deserializer=social_dot_mixi_dot_application_dot_service_dot_application__api_dot_v1_dot_service__pb2.SendDirectMessageToCommunityMemberResponse.FromString,
                _registered_method=True)


class ApplicationServiceServicer:
    """mixi2 アプリケーションサービスです。
    """

    def GetUsers(self, request, context):
        """指定したユーザーIDリストに対応するユーザー情報を取得します。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPosts(self, request, context):
        """指定したポストIDリストに対応するポスト情報を取得します。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCommunities(self, request, context):
        """指定したコミュニティIDリストに対応するコミュニティ情報を取得します。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreatePost(self, request, context):
        """ポストを作成します（返信/引用/コミュニティポスト・メディア添付等に対応）。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeletePost(self, request, context):
        """指定したポストを削除します。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InitiatePostMediaUpload(self, request, context):
        """ポストやメッセージ（ルーム送信/DM）に添付するメディアのアップロードを開始し、アップロード先URLを発行します。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPostMediaStatus(self, request, context):
        """指定したメディアIDのアップロード/処理状況を取得します。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCommunityTimeline(self, request, context):
        """指定したコミュニティのタイムライン（ポスト一覧）を取得します。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCommunityMemberList(self, request, context):
        """指定したコミュニティのメンバー一覧をページング付きで取得します。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RestrictCommunityPost(self, request, context):
        """指定したポストをコミュニティのタイムラインから非表示にします（削除ではありません）。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCommunitiesUsingApplication(self, request, context):
        """アプリケーションが導入されているコミュニティ一覧と、各コミュニティが利用しているアプリケーションバージョン情報を取得します。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendChatMessage(self, request, context):
        """指定したルームにチャットメッセージを送信します（テキスト/メディア添付）。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStamps(self, request, context):
        """スタンプ一覧を取得します。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddStampToPost(self, request, context):
        """指定したポストにスタンプを付与します。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendDirectMessageToCommunityMember(self, request, context):
        """コミュニティメンバーにダイレクトメッセージを送信します。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ApplicationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetUsers': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUsers,
                    request_deserializer=social_dot_mixi_dot_application_dot_service_dot_application__api_dot_v1_dot_service__pb2.GetUsersRequest.FromString,
                    response_serializer=social_dot_mixi_dot_application_dot_service_dot_application__api_dot_v1_dot_service__pb2.GetUsersResponse.SerializeToString,
            ),
            'GetPosts': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPosts,
                    request_deserializer=social_dot_mixi_dot_application_dot_service_dot_application__api_dot_v1_dot_service__pb2.GetPostsRequest.FromString,
                    response_serializer=social_dot_mixi_dot_application_dot_service_dot_application__api_dot_v1_dot_service__pb2.GetPostsResponse.SerializeToString,
            ),
            'GetCommunities': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCommunities,
                    request_deserializer=social_dot_mixi_dot_application_dot_service_dot_application__api_dot_v1_dot_service__pb2.GetCommunitiesRequest.FromString,
                    response_serializer=social_dot_mixi_dot_application_dot_service_dot_application__api_dot_v1_dot_service__pb2.GetCommunitiesResponse.SerializeToString,
            ),
            'CreatePost': grpc.unary_unary_rpc_method_handler(
                    servicer.CreatePost,
                    request_deserializer=social_dot_mixi_dot_application_dot_service_dot_application__api_dot_v1_dot_service__pb2.CreatePostRequest.FromString,
                    response_serializer=social_dot_mixi_dot_application_dot_service_dot_application__api_dot_v1_dot_service__pb2.CreatePostResponse.SerializeToString,
            ),
            'DeletePost': grpc.unary_unary_rpc_method_handler(
                    servicer.DeletePost,
                    request_deserializer=social_dot_mixi_dot_application_dot_service_dot_application__api_dot_v1_dot_service__pb2.DeletePostRequest.FromString,
                    response_serializer=social_dot_mixi_dot_application_dot_service_dot_application__api_dot_v1_dot_service__pb2.DeletePostResponse.SerializeToString,
            ),
            'InitiatePostMediaUpload': grpc.unary_unary_rpc_method_handler(
                    servicer.InitiatePostMediaUpload,
                    request_deserializer=social_dot_mixi_dot_application_dot_service_dot_application__api_dot_v1_dot_service__pb2.InitiatePostMediaUploadRequest.FromString,
                    response_serializer=social_dot_mixi_dot_application_dot_service_dot_application__api_dot_v1_dot_service__pb2.InitiatePostMediaUploadResponse.SerializeToString,
            ),
            'GetPostMediaStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPostMediaStatus,
                    request_deserializer=social_dot_mixi_dot_application_dot_service_dot_application__api_dot_v1_dot_service__pb2.GetPostMediaStatusRequest.FromString,
                    response_serializer=social_dot_mixi_dot_application_dot_service_dot_application__api_dot_v1_dot_service__pb2.GetPostMediaStatusResponse.SerializeToString,
            ),
            'GetCommunityTimeline': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCommunityTimeline,
                    request_deserializer=social_dot_mixi_dot_application_dot_service_dot_application__api_dot_v1_dot_service__pb2.GetCommunityTimelineRequest.FromString,
                    response_serializer=social_dot_mixi_dot_application_dot_service_dot_application__api_dot_v1_dot_service__pb2.GetCommunityTimelineResponse.SerializeToString,
            ),
            'GetCommunityMemberList': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCommunityMemberList,
                    request_deserializer=social_dot_mixi_dot_application_dot_service_dot_application__api_dot_v1_dot_service__pb2.GetCommunityMemberListRequest.FromString,
                    response_serializer=social_dot_mixi_dot_application_dot_service_dot_application__api_dot_v1_dot_service__pb2.GetCommunityMemberListResponse.SerializeToString,
            ),
            'RestrictCommunityPost': grpc.unary_unary_rpc_method_handler(
                    servicer.RestrictCommunityPost,
                    request_deserializer=social_dot_mixi_dot_application_dot_service_dot_application__api_dot_v1_dot_service__pb2.RestrictCommunityPostRequest.FromString,
                    response_serializer=social_dot_mixi_dot_application_dot_service_dot_application__api_dot_v1_dot_service__pb2.RestrictCommunityPostResponse.SerializeToString,
            ),
            'GetCommunitiesUsingApplication': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCommunitiesUsingApplication,
                    request_deserializer=social_dot_mixi_dot_application_dot_service_dot_application__api_dot_v1_dot_service__pb2.GetCommunitiesUsingApplicationRequest.FromString,
                    response_serializer=social_dot_mixi_dot_application_dot_service_dot_application__api_dot_v1_dot_service__pb2.GetCommunitiesUsingApplicationResponse.SerializeToString,
            ),
            'SendChatMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.SendChatMessage,
                    request_deserializer=social_dot_mixi_dot_application_dot_service_dot_application__api_dot_v1_dot_service__pb2.SendChatMessageRequest.FromString,
                    response_serializer=social_dot_mixi_dot_application_dot_service_dot_application__api_dot_v1_dot_service__pb2.SendChatMessageResponse.SerializeToString,
            ),
            'GetStamps': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStamps,
                    request_deserializer=social_dot_mixi_dot_application_dot_service_dot_application__api_dot_v1_dot_service__pb2.GetStampsRequest.FromString,
                    response_serializer=social_dot_mixi_dot_application_dot_service_dot_application__api_dot_v1_dot_service__pb2.GetStampsResponse.SerializeToString,
            ),
            'AddStampToPost': grpc.unary_unary_rpc_method_handler(
                    servicer.AddStampToPost,
                    request_deserializer=social_dot_mixi_dot_application_dot_service_dot_application__api_dot_v1_dot_service__pb2.AddStampToPostRequest.FromString,
                    response_serializer=social_dot_mixi_dot_application_dot_service_dot_application__api_dot_v1_dot_service__pb2.AddStampToPostResponse.SerializeToString,
            ),
            'SendDirectMessageToCommunityMember': grpc.unary_unary_rpc_method_handler(
                    servicer.SendDirectMessageToCommunityMember,
                    request_deserializer=social_dot_mixi_dot_application_dot_service_dot_application__api_dot_v1_dot_service__pb2.SendDirectMessageToCommunityMemberRequest.FromString,
                    response_serializer=social_dot_mixi_dot_application_dot_service_dot_application__api_dot_v1_dot_service__pb2.SendDirectMessageToCommunityMemberResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'social.mixi.application.service.application_api.v1.ApplicationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('social.mixi.application.service.application_api.v1.ApplicationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ApplicationService:
    """mixi2 アプリケーションサービスです。
    """

    @staticmethod
    def GetUsers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/social.mixi.application.service.application_api.v1.ApplicationService/GetUsers',
            social_dot_mixi_dot_application_dot_service_dot_application__api_dot_v1_dot_service__pb2.GetUsersRequest.SerializeToString,
            social_dot_mixi_dot_application_dot_service_dot_application__api_dot_v1_dot_service__pb2.GetUsersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPosts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/social.mixi.application.service.application_api.v1.ApplicationService/GetPosts',
            social_dot_mixi_dot_application_dot_service_dot_application__api_dot_v1_dot_service__pb2.GetPostsRequest.SerializeToString,
            social_dot_mixi_dot_application_dot_service_dot_application__api_dot_v1_dot_service__pb2.GetPostsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCommunities(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/social.mixi.application.service.application_api.v1.ApplicationService/GetCommunities',
            social_dot_mixi_dot_application_dot_service_dot_application__api_dot_v1_dot_service__pb2.GetCommunitiesRequest.SerializeToString,
            social_dot_mixi_dot_application_dot_service_dot_application__api_dot_v1_dot_service__pb2.GetCommunitiesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreatePost(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/social.mixi.application.service.application_api.v1.ApplicationService/CreatePost',
            social_dot_mixi_dot_application_dot_service_dot_application__api_dot_v1_dot_service__pb2.CreatePostRequest.SerializeToString,
            social_dot_mixi_dot_application_dot_service_dot_application__api_dot_v1_dot_service__pb2.CreatePostResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeletePost(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/social.mixi.application.service.application_api.v1.ApplicationService/DeletePost',
            social_dot_mixi_dot_application_dot_service_dot_application__api_dot_v1_dot_service__pb2.DeletePostRequest.SerializeToString,
            social_dot_mixi_dot_application_dot_service_dot_application__api_dot_v1_dot_service__pb2.DeletePostResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InitiatePostMediaUpload(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/social.mixi.application.service.application_api.v1.ApplicationService/InitiatePostMediaUpload',
            social_dot_mixi_dot_application_dot_service_dot_application__api_dot_v1_dot_service__pb2.InitiatePostMediaUploadRequest.SerializeToString,
            social_dot_mixi_dot_application_dot_service_dot_application__api_dot_v1_dot_service__pb2.InitiatePostMediaUploadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPostMediaStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/social.mixi.application.service.application_api.v1.ApplicationService/GetPostMediaStatus',
            social_dot_mixi_dot_application_dot_service_dot_application__api_dot_v1_dot_service__pb2.GetPostMediaStatusRequest.SerializeToString,
            social_dot_mixi_dot_application_dot_service_dot_application__api_dot_v1_dot_service__pb2.GetPostMediaStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCommunityTimeline(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/social.mixi.application.service.application_api.v1.ApplicationService/GetCommunityTimeline',
            social_dot_mixi_dot_application_dot_service_dot_application__api_dot_v1_dot_service__pb2.GetCommunityTimelineRequest.SerializeToString,
            social_dot_mixi_dot_application_dot_service_dot_application__api_dot_v1_dot_service__pb2.GetCommunityTimelineResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCommunityMemberList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/social.mixi.application.service.application_api.v1.ApplicationService/GetCommunityMemberList',
            social_dot_mixi_dot_application_dot_service_dot_application__api_dot_v1_dot_service__pb2.GetCommunityMemberListRequest.SerializeToString,
            social_dot_mixi_dot_application_dot_service_dot_application__api_dot_v1_dot_service__pb2.GetCommunityMemberListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RestrictCommunityPost(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/social.mixi.application.service.application_api.v1.ApplicationService/RestrictCommunityPost',
            social_dot_mixi_dot_application_dot_service_dot_application__api_dot_v1_dot_service__pb2.RestrictCommunityPostRequest.SerializeToString,
            social_dot_mixi_dot_application_dot_service_dot_application__api_dot_v1_dot_service__pb2.RestrictCommunityPostResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCommunitiesUsingApplication(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/social.mixi.application.service.application_api.v1.ApplicationService/GetCommunitiesUsingApplication',
            social_dot_mixi_dot_application_dot_service_dot_application__api_dot_v1_dot_service__pb2.GetCommunitiesUsingApplicationRequest.SerializeToString,
            social_dot_mixi_dot_application_dot_service_dot_application__api_dot_v1_dot_service__pb2.GetCommunitiesUsingApplicationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendChatMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/social.mixi.application.service.application_api.v1.ApplicationService/SendChatMessage',
            social_dot_mixi_dot_application_dot_service_dot_application__api_dot_v1_dot_service__pb2.SendChatMessageRequest.SerializeToString,
            social_dot_mixi_dot_application_dot_service_dot_application__api_dot_v1_dot_service__pb2.SendChatMessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStamps(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/social.mixi.application.service.application_api.v1.ApplicationService/GetStamps',
            social_dot_mixi_dot_application_dot_service_dot_application__api_dot_v1_dot_service__pb2.GetStampsRequest.SerializeToString,
            social_dot_mixi_dot_application_dot_service_dot_application__api_dot_v1_dot_service__pb2.GetStampsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddStampToPost(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/social.mixi.application.service.application_api.v1.ApplicationService/AddStampToPost',
            social_dot_mixi_dot_application_dot_service_dot_application__api_dot_v1_dot_service__pb2.AddStampToPostRequest.SerializeToString,
            social_dot_mixi_dot_application_dot_service_dot_application__api_dot_v1_dot_service__pb2.AddStampToPostResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendDirectMessageToCommunityMember(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/social.mixi.application.service.application_api.v1.ApplicationService/SendDirectMessageToCommunityMember',
            social_dot_mixi_dot_application_dot_service_dot_application__api_dot_v1_dot_service__pb2.SendDirectMessageToCommunityMemberRequest.SerializeToString,
            social_dot_mixi_dot_application_dot_service_dot_application__api_dot_v1_dot_service__pb2.SendDirectMessageToCommunityMemberResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
